### ISSUE TITLE
Assertion Failure on Single-Core Devices

### ISSUE THREAD

**Issue by Adlai-Holler** [pinterest/PINCache#134]
Launching an app that uses PINCache on an iPhone 4 causes immediate assertion failure: `Max concurrent operations must be greater than 1. If it's one, just use a serial queue!`

Best bet is to remove this assertion – it feels over-eager IMO.

**Comment by garrettmoon** [comment]
I'm not positive it will *work* with a maxConcurrentOperations of 1. It might, but I'll need to test. I think the issue is this line:
`[[PINOperationQueue alloc] initWithMaxConcurrentOperations:[[NSProcessInfo processInfo] activeProcessorCount]];`

which should be
`[[PINOperationQueue alloc] initWithMaxConcurrentOperations:[[NSProcessInfo processInfo] activeProcessorCount] * 2];

**Comment by garrettmoon** [comment]
@Adlai-Holler Happy to discuss removing the assertion, but I think it actually catches a legitimate issue.
