### ISSUE TITLE
When i set object 1500 times(or more) in global_queue, it will cause UI no response

### ISSUE THREAD

**Issue by spWang** [pinterest/PINCache#150]
When i set object 1500 times(or more) in global_queue, it will cause UI no response
this is code:

#define timeStart() CGFloat start = CACurrentMediaTime();
#define timeEndLogDuration(); NSLog(@"duration:%f",CACurrentMediaTime() - start);

- (void)testThreadSafeForSet {
    PINCache *cache = [PINCache sharedCache];
    timeStart();
    for (int i = 0; i<1500; i++) {
        dispatch_async(dispatch_get_global_queue(0, 0), ^{
            //            LOGThreadEvery1000times();
            NSString *value = [NSString stringWithFormat:@"value~%d",i];
            NSString *key = [NSString stringWithFormat:@"key~%d",i];
            [cache setObject:value forKey:key];
//            [cache setObject:value forKey:key block:nil];
        });
    }
    timeEndLogDuration();
}

**Comment by garrettmoon** [comment]
@spWang Can you give more details or put up a failing unit test? I added this code to the unit tests and it passed for me.

**Comment by spWang** [comment]
I commit the  code in my github, and I hope you will see it. if my test is not correct,please tell me why, thank you very much!
https://github.com/spWang/PINTest

**Comment by garrettmoon** [comment]
@spWang thanks for posting the example, now I know the issue!

So this isn't a deadlock, what's happening is you're starving the main thread by doing tons of work on other threads.

Update to the latest PINCache, it has thread limiting built in so that it will only work on a finite number of threads. Then, instead of accessing the cache serially on a dispatch queue, use the block api (you can pass nil, i.e. `[cache setObject:value forKey:key block:nil];`). Literally updating to the latest and changing to use the block API will address the issue in your sample project.

You could also instead use the global low priority queue instead of creating your own. That also appears to address the issue. I'm not sure why GCD isn't prioritizing the main thread over a bunch of work on a default priority queue :/

Hope this helps!

**Comment by spWang** [comment]
Firts,thank you very much for helping me solve this problem.
now, I update the latest PINCache, after I read your code,I learned a lot of things.
so, I have another question, why PINCache does not have the exprie time to control the cache, I think it  will be needed in a lot of scene.

**Comment by garrettmoon** [comment]
It does! However you need to set it on the memory cache or disk cache separately. It's not exposed on the PINCache instance because it's unlikely you should have the same age limit on a memory and disk cache.

Here's how you can set it:
`cache.memoryCache.ageLimit = 60 * 60; // 1 hour`
`cache.diskCache.ageLimit = 60 * 60 * 24 * 30; // 30 days`
