### ISSUE TITLE
_dates is out of sync with the files on disk

### ISSUE THREAD

**Issue by yufanlusc** [pinterest/PINCache#183]
In enumerateWithBlock(Async) function, before we do the for loop, if we examine the _dates with the files on disk, like this:
`- (void)output
{
    NSArray *keys = @[ NSURLContentModificationDateKey, NSURLTotalFileAllocatedSizeKey ];
    
    NSError *error = nil;
    NSArray *files = [[NSFileManager defaultManager] contentsOfDirectoryAtURL:_cacheURL
                                                   includingPropertiesForKeys:keys
                                                                      options:NSDirectoryEnumerationSkipsHiddenFiles
                                                                        error:&error];
    PINDiskCacheError(error);
    
    NSLog(@"pre enumeration on _files: %@", files);
    NSLog(@"pre enumeration on _dates: %@", _dates);
    
    if ([files count] != [_dates count]) {
        NSLog(@"OOS"); // <--- breakpoint
    }
}`

We did this enumeration upon app entering background, and it could cause this OOS.
Any idea what could happen?

**Comment by garrettmoon** [comment]
@yufanlusc First of all, sorry for the super delayed reply, my GitHub notification settings were all outta wack :(

How far are this outta sync? I could see the file modification date not being set because the app crashed before it could be. If that were the case it wouldn't be read into _dates on startup. It's also possible that setting the attribute failed; we don't do much to handle failures there.

It's an interesting issue, especially if you're seeing it systemically. Any more info would be greatly appreciated.

**Comment by yufanlusc** [comment]
Thanks for the response! @garrettmoon 
And let me apologize, I think it's our fault to use PINCache in a wrong way. I don't think current PINCache has any problem.

Thanks!
